- autoload/maktaba/plugin.vim
- vroom/libraries.vroom
Fixes `maktaba#plugin#Get` and downstream functions like `maktaba#library#Require` to detect when a dirname like vim-PLUGINNAME has been added to vim's runtimepath.
I haven't done any serious profiling, but since this code is not a hotspot and only executes at most once per plugin, I'm not too worried about performance regressions. I did a quick check of `time vim -c 'quit'` and my vim startup was about the same before and after.
Partially fixes #112.
Support for checking addon-info.json files to support arbitrary directory names is yet to come, but will be harder to implement without screwing performance.
> Detect uncanonicalized plugin dir names on runtimepath

- autoload/maktaba/syscall.vim
- doc/maktaba.txt
- vroom/system.vroom
Example usage:
```vim
let l:cmd = call maktaba#syscall#Create(['/bin/sleep', '3'])
call l:cmd.CallAsync('CallMeMaybe')
call l:cmd.CallAsync(maktaba#function#Create('CallMeMaybe'))
```
Asynchronous execution works by executing the command in the background
which, after the command is completed, executes "vim --remote-expr" that
uses the vim v:servername to find the originating server and call the
callback.
Requirements:
- vim compiled with +clientserver
- vim started with --servername
- DISPLAY set to same X where vim is running (e.g. when over ssh)
Inspired by pydev/AsyncCommand.
Closes google/vim-maktaba#116.
> Implement asynchronous execution in Maktaba.

- autoload/maktaba/syscall.vim
When asynchonous calls are not available due to v:servername not being set,
the message of the exception thrown has a missing concat operator.
> Fix typo, missing string concatenation.

- autoload/maktaba/syscall.vim
- doc/maktaba.txt
Forward errors to handler even in sync fallback and get rid of throw_errors arg that didn't work as advertised.
Also switch from ERROR(ShellError) to ERROR(MissingFeature) and remove return value from CallAsync.
Fixes #121.
> Fix error cases for Syscall.CallAsync

- autoload/maktaba/syscall.vim
- vroom/system.vroom
Even if .WithStdin is invoked on a Syscall, when runnin asynchronously,
this is ignored.
Fix the issue and add a test case for it.
Closes google/vim-maktaba#127.
> Fix issue: Syscall.CallAsync ignores WithStdin.

- .travis.yml
- examples/helloworld/bootstrap.vim
Update helloworld's bootstrap.vim so it falls back to installing maktaba from the containing repo if it's not available otherwise. In particular, this fixes the vroom tests since so they have their maktaba dependency satisfied.
Also re-enables tests on Travis CI now that they pass again.
Fixes #68.
> Fix helloworld to find maktaba from containing repo

- autoload/maktaba/path.vim
I happened to notice a bug that makes `maktaba#path#Exists()` depend on the `'suffixes'` and `'wildignore'` settings:
```vim
:set wildignore+=*.vim
:echo maktaba#path#Exists('autoload/maktaba.vim')
```
> Fix maktaba#path#Exists() to be independent of user options

- autoload/maktaba/extension.vim
- autoload/maktaba/plugin.vim
- doc/maktaba.txt
- vroom/plugin.vroom
- vroom/pluginextensions.vroom
Create a way for plugins to register extensions (arbitrary optionally-validated dicts) against other plugins, avoiding the need to split out small library plugins just for registration (e.g. `vim-codefmtlib`) .
Fixes #130.
> Implement a registry mechanism for plugins

- autoload/maktaba/path.vim
- doc/maktaba.txt
Optimizes `maktaba#path#Dirname` to reduce the number of calls to some hot spots (`maktaba#path#Split`, `maktaba#path#Join` and `maktaba#path#RootComponent`).
Excerpt from my profiling results before and after:
```
count  total (s)   self (s)  function
-   45   0.104520   0.003073  maktaba#plugin#GetOrInstall()
+   45   0.082889   0.002962  maktaba#plugin#GetOrInstall()
-    1   0.073113   0.000327  maktaba#plugin#Detect()
+    1   0.060265   0.000320  maktaba#plugin#Detect()
-  325   0.052764   0.030335  maktaba#path#Join()
+  207   0.022298   0.014177  maktaba#path#Join()
-  118   0.038825   0.003174  maktaba#path#Dirname()
+  118   0.018949   0.000688  maktaba#path#Dirname()
+  118   0.018261   0.017616  <SNR>8_SplitLast()
-   29   0.018785   0.001267  maktaba#plugin#Source()
+   29 …
```
> Optimize critical maktaba#path# functions

- autoload/maktaba/extension.vim
Per suggestion in #130, this adds some logging when creating an extension registry.
> Log a message when an extension registry is created.

- autoload/maktaba/plugin.vim
More performance optimizations in `maktaba#plugin#Get` and `maktaba#plugin#Detect` that help significantly when large numbers of plugins are installed.
Excerpts from my profiling results before and after:
```
FUNCTION  maktaba#plugin#Get()                                                                       
Called 101 times
-Total time:   0.261599                                                                              
+Total time:   0.075955                                                                              
- Self time:   0.025052                                                                              
+ Self time:   0.002005                                                                              
count  total (s)   self (s)
-  101              0.000245   if …
```
> Optimize maktaba#plugin#Get and Detect

- autoload/maktaba/json.vim
- doc/maktaba.txt
- vroom/json.vroom
This implementation is not yet used for `maktaba#plugin#AddonInfo` because it adds a small but measurable delay to vim startup (~100ms out of ~800ms on my system). It should be fine as a non-python fallback, though, given the python implementation has good performance.
Fixes #35.
> Implement JSON parsing and formatting support in maktaba#json#

- autoload/maktaba/json.vim
This avoids the need for the Python implementation (#152) to duplicate the fallbacks to the default custom values, and generally allows it to share the Vimscript setup in `maktaba#json#Parse()`.
> Explicitly include the default JSON custom values when parsing.

- autoload/maktaba.vim
- autoload/maktaba/json.vim
- autoload/maktaba/json/python.vim
- doc/maktaba.txt
- python/maktabajson.py
- vroom/json-vimscript.vroom
Use Python's json library for `maktaba#json#Parse()` and `maktaba#json#Format()` where possible (if Vim is compiled with `+python`, and if we're using Vim >= 7.3.1042). This is both faster and more-correct.
Fixes #152.
> Add a Python implementation of JSON parsing and formatting functions.

- autoload/maktaba/json.vim
This commit disables python in json module when running under Neovim.
Maktaba's maktabajson.py uses bindeval, which is not implemented in neovim and
causes error messages [Bug #158](https://github.com/google/vim-maktaba/issues/158).
> Disable python use in Neovim

- autoload/maktaba/json.vim
- python/maktabajson.py
- vroom/json-vimscript.vroom
- vroom/json.vroom
I switched to compact JSON representation (without whitespace for padding) in the vimscript and python implementations to make the output consistent with the native vim implementation's output (just to keep our testing simple), but it shouldn't affect much in practice and we can just switch it back and make our tests more flexible if we run into issues.
Fixes #166.
> Support native JSON support in vim 7.4.1304 and later

- autoload/maktaba/json.vim
- python/maktabajson.py
- vroom/json-vimscript.vroom
- vroom/json.vroom
Fixes #170.
Note I had to disable native support in the 1304–1429 range since there's no good way to build the new NaN/Infinity behavior on top of that implementation that errors out.
> Support JSON NaN and Infinity values for consistency w/ native

- vroom/function.vroom
Apparently this misfeature was fixed in vim 7.4.1581.
Fixes #169.
> Delete failing vroom demonstrating funcref misfeature

- autoload/maktaba/enum.vim
- autoload/maktaba/function.vim
- autoload/maktaba/value.vim
- doc/maktaba.txt
~~Modifies maktaba#value#IsEqual to work around a behavior change in
7.4.1875…~~
Switches code in IsCallable an IsEnum to explicitly check if Funcrefs have the same name using explicit `maktaba#function#HasSameName` helper. `maktaba#value#IsEqual` behavior stays the same, meaning it will have slightly different behavior when patch 1875 is present.
Fixes #172.
> Fix IsCallable and IsEnum checking on 7.4.1875 and later

- autoload/maktaba/path.vim
- doc/maktaba.txt
- vroom/path.vroom
This was apparently a regression in 5021b3f from years ago. Note Dirname behavior was correct in itself, but it broke the invariant that `Join([Dirname(X), Basename(X)])` should be equivalent to the original path `X`.
Fixes #177.
> Fix path#Basename handling for bare filenames (was always empty string)

- autoload/maktaba/syscall.vim
- doc/maktaba.txt
- vroom/system.vroom
Simplify the Syscall.CallAsync interface. This removes the `env_dict` arg from the callback, but still supports the old signature during a deprecation period as a legacy fallback.
I've found the callback signature confusing in practice, and upcoming CallAsync enhancements will make CallAsync more viable and potentially add a lot more usage, so now's the time to get any migrations underway.
Fixes #180.
@stgpetrovic
> Add support for Syscall.CallAsync callback that doesn't accept env_dict

- autoload/maktaba/syscall.vim
- vroom/system.vroom
> Shout errors from CallAsync callback to avoid silent failures

- autoload/maktaba/syscall.vim
- autoload/maktaba/syscall/invocation.vim
- doc/maktaba.txt
- vroom/system.vroom
Returns a SyscallInvocation dict from CallAsync calls that encapsulates
the invocation's status and output. This can be extended in future
changes to allow other types of interactions. It's also passed into the
callbacks (backwards-compatible with the result_dict value), so if other
data needs to be passed into callbacks in the future it can be attached
to the invocation.
> Change Syscall.CallAsync to return an explicit SyscallInvocation.

- .travis.yml
- autoload/maktaba/syscall.vim
- autoload/maktaba/syscall/async.vim
- autoload/maktaba/syscall/clientserver.vim
- autoload/maktaba/syscall/invocation.vim
- doc/maktaba.txt
- vroom/system-vimjob.vroom
- vroom/system.vroom
Enhances Syscall.CallAsync to invoke syscalls as native vim jobs if the vim instance supports them, and demotes the clientserver-based implementation to "legacy" (to be eventually removed in #190).
Resolves #184.
> Add vim job support to Syscall.CallAsync

- autoload/maktaba/json.vim
Fixes #195.
I did some profiling for fun. Couldn't measure a reliable improvement in overall startup time, but I can see from the `--startuptime` output that it's saving ~10ms of overhead loading json.vim. See `self+sourced` and `self` columns below:
```
times in msec
clock   self+sourced   self:  sourced script
clock   elapsed:              other lines
…
- 035.453  000.027  000.027: sourcing /home/dbarnett/.vim/plugged/vim-maktaba/autoload/maktaba/json/python.vim
- 044.654  009.319  009.292: sourcing /home/dbarnett/.vim/plugged/vim-maktaba/autoload/maktaba/json.vim
+ 033.384  000.252  000.252: sourcing /home/dbarnett/.vim/plugged/vim-maktaba/autoload/maktaba/json.vim
```
> Skip python init for JSON when python implementation isn't needed

- autoload/maktaba.vim
- autoload/maktaba/buffer.vim
- autoload/maktaba/python.vim
- doc/maktaba.txt
Also adds a Python section to Maktaba's help to detail some of the compatibility considerations and a warning on `maktaba#python#Eval` about a gotcha with accessing local variable scopes.
Fixes #193.
> Add python3 support for maktaba#python# and maktaba#buffer#Overwrite

- autoload/maktaba/path.vim
- autoload/maktaba/plugin.vim
- autoload/maktaba/rtp.vim
- doc/maktaba.txt
- vroom/path.vroom
- vroom/plugin.vroom
Also improves `maktaba#path#MakeRelative` to preserve trailing slash and adds a `maktaba#path#StripTrailingSlash()`.
A little profiling since I was concerned about hotspot performance regressions…
Profile summary before this change:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
874   0.070503   0.042762  maktaba#path#Join()
3296              0.042045  maktaba#path#AsDir()
42   0.040494   0.025003  maktaba#rtp#LeafDirs()
658   0.021195   0.014652  maktaba#setting#ParseHandle()
41   0.054411   0.012718  maktaba#rtp#Join()
559   0.018049   0.012574  maktaba#value#Focus()
610   0.056664   0.012383  maktaba#plugin#Flag()
3144              0.011213  maktaba#ensure#TypeMatches()
2517              0.009126  maktaba#path#RootComponent()
132   0.124043   0.007136 …
```
> Preserve trailing slash in maktaba#path#Split

- autoload/maktaba/syscall.vim
- autoload/maktaba/syscall/async.vim
- vroom/system-vimjob.vroom
syscall functions assume shell-like behavior, but job_start doesn't use
a shell.
Fixes #205
> Use shell for CallAsync with vim jobs

- autoload/maktaba/log.vim
- doc/maktaba.txt
- vroom/log.vroom
These changes help log handlers treat log entries as opaque data structures so maktaba can evolve the format as needed w/o having to coordinate versioning with callers. Entry format will be changed slightly in #103 after callers have a chance to migrate to this helper.
Note the "Not enough arguments" fallback could conceivably cause performance regressions until the callers are updated if there's a ton of logging, but I tried it out on a fairly heavy vim configuration with a lot of plugins and logging and I couldn't measure a reliable performance regression comparing `time vim -c quit` output with and without.
> Implement maktaba#log#GetFormattedEntries and support 1-arg handler

- autoload/maktaba/log.vim
- doc/maktaba.txt
- vroom/log.vroom
Notifies at WARN level by default, and adds a `maktaba#log#SetNotificationLevel` hook to override that level.
Fixes #185.
Note: Any pre-existing callers and handlers that print log messages may trigger duplicate notifications until those are cleaned up. In cases where avoiding that is particularly important, they can detect whether `maktaba#log#SetNotificationLevel` exists.
> Notify user for messages logged at WARN or above by default.

- autoload/maktaba/selector.vim
- doc/maktaba.txt
- vroom/selector.vroom
Fixes #208.
This is all merged from vim-selector's autoload/selector.vim and main.vroom, but without the legacy selector#OpenWindow API.
Next step will be to gut the vim-selector implementation once users have had some time to update maktaba and make it delegate to maktaba for all the non-legacy implementation, and then to mark the whole vim-selector plugin deprecated.
> Add a maktaba#selector# interface for launching selector windows

- .travis.yml
Updates to use vroom 0.13.0 which fixes support for newer versions of neovim python client (0.1.6 and newer). Also removes a `--allow-external` option which the pip script seems to no longer support and apparently no longer needs.
Note that most vroom tests still hang in neovim mode (see google/vroom#83 and google/vroom#100), so we are not ready to remove the `allow_failures` override for neovim tests.
> Update .travis.yml to use vroom 0.13.0 (w/ neovim fix)

- autoload/maktaba/selector.vim
It's confusing and probably wrong to perform an edit. So, change to a no-op.
> Change the default key to be a NoOp for Selector

- autoload/maktaba/ui/selector.vim
- doc/maktaba.txt
- vroom/selector.vroom
Move the selector to a ui subdirectory. 
There are a couple more helpers I would like to add -- for example, for managing popups, textprop, rich text windows. Having a ui subdirectory ought to be useful for that. It's also only 3 more characters than the existing function path.
> Move selector to a ui subdirectory

- autoload/maktaba/ui/README.md
- autoload/maktaba/ui/selector.vim
- vroom/selector.vroom
This adds a readme for the UI subdirectory. Not doing any transformation -- just describing what currently exists. I think a longer tutorial should live in the wiki, but this is useful for a basic how-to.
Assumes https://github.com/google/vim-maktaba/pull/228
> Readme for UI package

- autoload/maktaba/syscall.vim
- vroom/system.vroom
Use `terminal` - if available - for foreground syscalls that have `pause` enabled. This gives it some nicer behavior in Vim >= 8 and Neovim.
> use `terminal` for foreground syscalls with pause enabled

- autoload/maktaba/python.vim
Helps with #231 by surfacing more details about where it tried to import the module from and the actual error thrown in case it's something more interesting than ModuleNotFoundError.
> Fail #python#ImportModule with clearer errors

- python/maktaba.py
Using "is" or "is not" operators with a string literal now produces a SyntaxWarning in python 3.8 (https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior), and the warning seems to cause some versions of neovim to blow up in cases like #231.
> Remove deprecated "is not" usage in maktaba.py

- .travis.yml
- autoload/maktaba/syscall.vim
- autoload/maktaba/syscall/neovim.vim
- doc/maktaba.txt
- vroom/system-job.vroom
- vroom/system-vimjob.vroom
Hello!
I think I've managed to get support for neovim's jobcontrol (#125) working (I've tested it manually with [vim-coverage](https://github.com/google/vim-coverage), which wasn't working for me and caused me to try and solve this in the first place).
However, in order to get system-vimjob.vroom to succeed, I need to pass vroom `--shell-delay .25` (by default vim's delay is 0.25 and neovim's is 0.0).  Here's an example failure:
```
└─ $ vroom --neovim vroom/system-vimjob.vroom
vroom/system-vimjob.vroom
FAILED on line 45: Multiple failures:
Expected system call not received.
Got no chance to inject response:
EXPECT:        echo hi (regex mode)
Failed command on line 45:
:let g:invocation = AsyncWait(g:syscall.CallAsync('Callback', 0), 2)
Queued system controls are:
EXPECT:        echo hi …
```
> Add native job support for neovim.

- autoload/maktaba/ui/selector.vim
Process key maps without waiting for longer global mappings that
start with the same keys.
Sync with https://github.com/google/vim-selector/pull/11.
> Ignore global maps when processing selector keys

- autoload/maktaba/flags.vim
- autoload/maktaba/syscall.vim
No change to logic. This prefers "allowlist" to "whitelist" for the sake
of using inclusive terminology.
> Replace "whitelist" with more inclusive terminology

- autoload/maktaba/ui/selector.vim
Produce tab character instead of a literal `\t`.
> Fix tab-character expansion in printf

- autoload/maktaba/ui/selector.vim
Using the help menu `H` in selector window sets global nomodifiable and readonly options.
Files opened from the selector menu are then locked for editing.
Restore nomodifiable and readonly options locally so they only apply to the selector window.
> Avoid setting global nomodifiable in selector help
